# src/ports/signer_port.py
class SignerPort:
    def public_key(self) -> bytes: ...
    def sign(self, payload: bytes) -> bytes: ...
    def verify(self, payload: bytes, signature: bytes) -> bool: ...
